//! Declarative cleanup rules. A rule says: a directory with this name, inside
//! a project of these ecosystems, is (safe | review) to remove because it is
//! regenerated by this command.
//!
//! Rules only ever match **directories**. Files are never removed by rules.

use crate::model::{ArtifactCategory, Safety, Stack};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CleanupRule {
    /// Unique id, e.g. `node_modules` or `rust-target`.
    pub id: String,
    /// Directory name to match. Supports `*` wildcards (`*.egg-info`).
    pub pattern: String,
    /// Ecosystems this rule applies to. Empty means every project.
    #[serde(default)]
    pub ecosystems: Vec<Stack>,
    pub safety: Safety,
    #[serde(default = "default_true")]
    pub regeneratable: bool,
    #[serde(default = "default_category")]
    pub category: ArtifactCategory,
    /// One sentence answering "why can this be removed?".
    #[serde(default)]
    pub explanation: String,
    /// Command that recreates the directory, when there is one.
    #[serde(default)]
    pub restore_hint: Option<String>,
    #[serde(default)]
    pub builtin: bool,
}

fn default_true() -> bool {
    true
}

fn default_category() -> ArtifactCategory {
    ArtifactCategory::Other
}

impl CleanupRule {
    fn new(
        id: &str,
        pattern: &str,
        ecosystems: &[Stack],
        safety: Safety,
        category: ArtifactCategory,
        explanation: &str,
        restore_hint: Option<&str>,
    ) -> Self {
        CleanupRule {
            id: id.to_string(),
            pattern: pattern.to_string(),
            ecosystems: ecosystems.to_vec(),
            safety,
            regeneratable: true,
            category,
            explanation: explanation.to_string(),
            restore_hint: restore_hint.map(str::to_string),
            builtin: true,
        }
    }

    pub fn matches_name(&self, name: &str) -> bool {
        glob_match(&self.pattern, name)
    }

    pub fn applies_to(&self, stacks: &[Stack]) -> bool {
        self.ecosystems.is_empty() || self.ecosystems.iter().any(|e| stacks.contains(e))
    }
}

/// The active set of rules: built-ins plus user-defined ones.
#[derive(Debug, Clone)]
pub struct RuleSet {
    rules: Vec<CleanupRule>,
    /// User-defined protected name patterns, on top of [`PROTECTED_PATTERNS`].
    extra_protected: Vec<String>,
}

impl Default for RuleSet {
    fn default() -> Self {
        RuleSet::builtin()
    }
}

impl RuleSet {
    pub fn builtin() -> Self {
        RuleSet {
            rules: builtin_rules(),
            extra_protected: Vec::new(),
        }
    }

    /// Built-in rules plus custom ones. Custom rules take precedence when both
    /// match the same directory in the same ecosystem. `protected_patterns`
    /// are extra names that must never be treated as artifacts.
    pub fn with_custom(custom: &[CleanupRule], protected_patterns: &[String]) -> Self {
        let extra_protected: Vec<String> = protected_patterns
            .iter()
            .map(|p| p.trim().to_string())
            .filter(|p| !p.is_empty())
            .collect();
        let is_protected = |name: &str| {
            is_protected_name(name) || extra_protected.iter().any(|p| glob_match(p, name))
        };
        let mut rules: Vec<CleanupRule> = custom
            .iter()
            .filter(|r| !r.pattern.trim().is_empty() && !is_protected(&r.pattern))
            .cloned()
            .map(|mut r| {
                r.builtin = false;
                r
            })
            .collect();
        rules.extend(builtin_rules());
        RuleSet {
            rules,
            extra_protected,
        }
    }

    /// Built-in protected patterns plus the user's own.
    pub fn is_protected(&self, name: &str) -> bool {
        is_protected_name(name) || self.extra_protected.iter().any(|p| glob_match(p, name))
    }

    pub fn rules(&self) -> &[CleanupRule] {
        &self.rules
    }

    pub fn find(&self, id: &str) -> Option<&CleanupRule> {
        self.rules.iter().find(|r| r.id == id)
    }

    /// True when a directory name matches *any* rule. Project discovery never
    /// descends into such directories: real projects do not live inside
    /// `node_modules/` or `target/`.
    pub fn is_barrier(&self, name: &str) -> bool {
        self.rules.iter().any(|r| r.matches_name(name))
    }

    /// Find the rule that applies to a directory inside a project with the
    /// given stacks. Ecosystem-specific rules win over generic ones.
    pub fn match_for(&self, name: &str, stacks: &[Stack]) -> Option<&CleanupRule> {
        if self.is_protected(name) {
            return None;
        }
        let mut generic: Option<&CleanupRule> = None;
        for rule in &self.rules {
            if !rule.matches_name(name) {
                continue;
            }
            if rule.ecosystems.is_empty() {
                generic.get_or_insert(rule);
                continue;
            }
            if rule.applies_to(stacks) {
                return Some(rule);
            }
        }
        generic
    }
}

fn builtin_rules() -> Vec<CleanupRule> {
    use ArtifactCategory::*;
    use Safety::*;
    use Stack::*;

    vec![
        // ---- Node -------------------------------------------------------
        CleanupRule::new(
            "node_modules",
            "node_modules",
            &[Node],
            Safe,
            NodeDependencies,
            "Installed packages generated from the lockfile.",
            Some("npm ci"),
        ),
        CleanupRule::new(
            "next",
            ".next",
            &[Node],
            Safe,
            BuildArtifacts,
            "Next.js build output and cache, rebuilt by `next build` or `next dev`.",
            Some("npx next build"),
        ),
        CleanupRule::new(
            "nuxt",
            ".nuxt",
            &[Node],
            Safe,
            BuildArtifacts,
            "Nuxt build directory, rebuilt by `nuxt build` or `nuxt dev`.",
            Some("npx nuxt build"),
        ),
        CleanupRule::new(
            "nuxt-output",
            ".output",
            &[Node],
            Safe,
            BuildArtifacts,
            "Nuxt / Nitro production output, rebuilt by `nuxt build`.",
            Some("npx nuxt build"),
        ),
        CleanupRule::new(
            "dist",
            "dist",
            &[Node, Python, Dart],
            Safe,
            BuildArtifacts,
            "Compiled output produced by the project's build step.",
            Some("run the project's build script"),
        ),
        CleanupRule::new(
            "build",
            "build",
            &[Node, Python, Gradle, Dart],
            Safe,
            BuildArtifacts,
            "Build output produced by the project's build step.",
            Some("run the project's build script"),
        ),
        CleanupRule::new(
            "coverage",
            "coverage",
            &[Node, Python],
            Safe,
            BuildArtifacts,
            "Test coverage reports, regenerated by running the test suite with coverage.",
            None,
        ),
        CleanupRule::new(
            "turbo",
            ".turbo",
            &[Node],
            Safe,
            Caches,
            "Turborepo task cache.",
            None,
        ),
        CleanupRule::new(
            "vite",
            ".vite",
            &[Node],
            Safe,
            Caches,
            "Vite dependency pre-bundle cache.",
            None,
        ),
        CleanupRule::new(
            "parcel-cache",
            ".parcel-cache",
            &[Node],
            Safe,
            Caches,
            "Parcel bundler cache.",
            None,
        ),
        CleanupRule::new(
            "svelte-kit",
            ".svelte-kit",
            &[Node],
            Safe,
            BuildArtifacts,
            "SvelteKit generated files, rebuilt by `svelte-kit sync` / `vite build`.",
            None,
        ),
        CleanupRule::new(
            "angular-cache",
            ".angular",
            &[Node],
            Safe,
            Caches,
            "Angular CLI build cache.",
            None,
        ),
        CleanupRule::new(
            "storybook-static",
            "storybook-static",
            &[Node],
            Safe,
            BuildArtifacts,
            "Static Storybook export, rebuilt by `storybook build`.",
            None,
        ),
        CleanupRule::new(
            "webpack-cache",
            ".webpack",
            &[Node],
            Safe,
            Caches,
            "Webpack build cache.",
            None,
        ),
        // ---- Rust / JVM ---------------------------------------------------
        CleanupRule::new(
            "rust-target",
            "target",
            &[Rust],
            Safe,
            RustTarget,
            "Cargo build directory with compiled dependencies and incremental caches.",
            Some("cargo build"),
        ),
        CleanupRule::new(
            "maven-target",
            "target",
            &[Maven],
            Safe,
            BuildArtifacts,
            "Maven build directory, rebuilt by `mvn package`.",
            Some("mvn package"),
        ),
        CleanupRule::new(
            "gradle-cache",
            ".gradle",
            &[Gradle],
            Review,
            Caches,
            "Project-local Gradle cache. Regenerated on the next build, but may hold wrapper distributions.",
            None,
        ),
        // ---- Python -------------------------------------------------------
        CleanupRule::new(
            "pycache",
            "__pycache__",
            &[Python],
            Safe,
            Caches,
            "Compiled Python bytecode, recreated automatically on import.",
            None,
        ),
        CleanupRule::new(
            "pytest-cache",
            ".pytest_cache",
            &[Python],
            Safe,
            Caches,
            "pytest cache directory.",
            None,
        ),
        CleanupRule::new(
            "mypy-cache",
            ".mypy_cache",
            &[Python],
            Safe,
            Caches,
            "mypy incremental type-check cache.",
            None,
        ),
        CleanupRule::new(
            "ruff-cache",
            ".ruff_cache",
            &[Python],
            Safe,
            Caches,
            "Ruff linter cache.",
            None,
        ),
        CleanupRule::new(
            "tox",
            ".tox",
            &[Python],
            Safe,
            PythonEnvironments,
            "tox virtual environments, recreated on the next tox run.",
            Some("tox"),
        ),
        CleanupRule::new(
            "nox",
            ".nox",
            &[Python],
            Safe,
            PythonEnvironments,
            "nox virtual environments, recreated on the next nox run.",
            Some("nox"),
        ),
        CleanupRule::new(
            "venv",
            ".venv",
            &[Python],
            Review,
            PythonEnvironments,
            "Virtual environment. Regeneratable from requirements, but may contain packages installed by hand.",
            Some("python -m venv .venv && pip install -r requirements.txt"),
        ),
        CleanupRule::new(
            "venv-plain",
            "venv",
            &[Python],
            Review,
            PythonEnvironments,
            "Virtual environment. Regeneratable from requirements, but may contain packages installed by hand.",
            Some("python -m venv venv && pip install -r requirements.txt"),
        ),
        CleanupRule::new(
            "egg-info",
            "*.egg-info",
            &[Python],
            Safe,
            BuildArtifacts,
            "Package metadata generated by setuptools.",
            None,
        ),
        // ---- Go / PHP / Ruby ------------------------------------------------
        CleanupRule::new(
            "vendor",
            "vendor",
            &[Go, Php, Ruby],
            Review,
            Other,
            "Vendored dependencies. Regenerated by `go mod vendor`, `composer install` or `bundle install`, but some projects commit patches here.",
            None,
        ),
        // ---- .NET -----------------------------------------------------------
        CleanupRule::new(
            "dotnet-bin",
            "bin",
            &[DotNet],
            Safe,
            BuildArtifacts,
            "MSBuild output directory, rebuilt by `dotnet build`.",
            Some("dotnet build"),
        ),
        CleanupRule::new(
            "dotnet-obj",
            "obj",
            &[DotNet, Unity],
            Safe,
            BuildArtifacts,
            "MSBuild intermediate objects, rebuilt by `dotnet build` or the Unity editor.",
            Some("dotnet build"),
        ),
        // ---- Swift / Elixir / Haskell / Zig ------------------------------------
        CleanupRule::new(
            "swift-build",
            ".build",
            &[Swift],
            Safe,
            BuildArtifacts,
            "Swift Package Manager build directory, rebuilt by `swift build`.",
            Some("swift build"),
        ),
        CleanupRule::new(
            "elixir-build",
            "_build",
            &[Elixir],
            Safe,
            BuildArtifacts,
            "Mix compiled output, rebuilt by `mix compile`.",
            Some("mix compile"),
        ),
        CleanupRule::new(
            "elixir-deps",
            "deps",
            &[Elixir],
            Review,
            Other,
            "Mix dependencies fetched by `mix deps.get`. Some projects patch dependencies in place.",
            Some("mix deps.get"),
        ),
        CleanupRule::new(
            "haskell-dist",
            "dist-newstyle",
            &[Haskell],
            Safe,
            BuildArtifacts,
            "Cabal build directory, rebuilt by `cabal build`.",
            Some("cabal build"),
        ),
        CleanupRule::new(
            "haskell-stack",
            ".stack-work",
            &[Haskell],
            Safe,
            BuildArtifacts,
            "Stack build directory, rebuilt by `stack build`.",
            Some("stack build"),
        ),
        CleanupRule::new(
            "zig-cache",
            "zig-cache",
            &[Zig],
            Safe,
            Caches,
            "Zig build cache.",
            Some("zig build"),
        ),
        CleanupRule::new(
            "zig-cache-hidden",
            ".zig-cache",
            &[Zig],
            Safe,
            Caches,
            "Zig build cache.",
            Some("zig build"),
        ),
        CleanupRule::new(
            "zig-out",
            "zig-out",
            &[Zig],
            Safe,
            BuildArtifacts,
            "Zig build output, rebuilt by `zig build`.",
            Some("zig build"),
        ),
        // ---- Unity / Terraform ---------------------------------------------------
        CleanupRule::new(
            "unity-library",
            "Library",
            &[Unity],
            Safe,
            Caches,
            "Unity asset import cache. Regenerated when the project is opened, which can take a while for large projects.",
            Some("open the project in the Unity editor"),
        ),
        CleanupRule::new(
            "unity-temp",
            "Temp",
            &[Unity],
            Safe,
            Caches,
            "Unity temporary build files.",
            None,
        ),
        CleanupRule::new(
            "unity-logs",
            "Logs",
            &[Unity],
            Safe,
            Caches,
            "Unity editor logs.",
            None,
        ),
        CleanupRule::new(
            "terraform",
            ".terraform",
            &[Terraform],
            Review,
            Other,
            "Downloaded providers and modules, restored by `terraform init`. State files outside this folder are never touched.",
            Some("terraform init"),
        ),
        // ---- iOS / Dart ------------------------------------------------------
        CleanupRule::new(
            "pods",
            "Pods",
            &[CocoaPods],
            Review,
            Other,
            "CocoaPods dependencies, reinstalled by `pod install`. Some teams commit this directory on purpose.",
            Some("pod install"),
        ),
        CleanupRule::new(
            "dart-tool",
            ".dart_tool",
            &[Dart],
            Safe,
            Caches,
            "Dart / Flutter tooling cache, recreated by `pub get`.",
            Some("flutter pub get"),
        ),
        // ---- Generic ---------------------------------------------------------
        CleanupRule::new(
            "cache",
            ".cache",
            &[],
            Safe,
            Caches,
            "Tool cache directory. Tools recreate it on demand.",
            None,
        ),
    ]
}

/// A directory that a candidate rule would match, for previews in Settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuleMatch {
    pub project_name: String,
    pub project_path: std::path::PathBuf,
    pub path: std::path::PathBuf,
    pub relative_path: String,
    pub bytes: u64,
    pub file_count: u64,
}

/// Find directories in the scanned projects that `pattern` would match if
/// it were a rule for `ecosystems` (empty = every project). Existing
/// artifacts, nested projects and protected names are skipped, the walk is
/// depth-limited, and at most `limit` matches are measured.
pub fn preview_matches(
    projects: &[crate::model::Project],
    pattern: &str,
    ecosystems: &[Stack],
    limit: usize,
    cancel: &std::sync::atomic::AtomicBool,
) -> Vec<RuleMatch> {
    use crate::scanner::size::{measure_tree, relative};
    use crate::scanner::traversal::is_default_ignored;
    use std::sync::atomic::Ordering;
    const MAX_DEPTH: usize = 5;
    let pattern = pattern.trim();
    if pattern.is_empty() || is_protected_name(pattern) {
        return Vec::new();
    }
    let project_paths: std::collections::HashSet<&std::path::Path> =
        projects.iter().map(|p| p.path.as_path()).collect();
    let mut out = Vec::new();
    'projects: for project in projects {
        if !ecosystems.is_empty() && !ecosystems.iter().any(|e| project.stacks.contains(e)) {
            continue;
        }
        let artifact_paths: std::collections::HashSet<&std::path::Path> =
            project.artifacts.iter().map(|a| a.path.as_path()).collect();
        let mut stack = vec![(project.path.clone(), 0usize)];
        while let Some((dir, depth)) = stack.pop() {
            if cancel.load(Ordering::Relaxed) {
                break 'projects;
            }
            let Ok(entries) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let Ok(ft) = entry.file_type() else { continue };
                if !ft.is_dir() || ft.is_symlink() {
                    continue;
                }
                let name = entry.file_name().to_string_lossy().into_owned();
                let path = entry.path();
                if is_default_ignored(&name)
                    || artifact_paths.contains(path.as_path())
                    || project_paths.contains(path.as_path())
                {
                    continue;
                }
                if glob_match(pattern, &name) && !is_protected_name(&name) {
                    let size = measure_tree(&path, cancel);
                    out.push(RuleMatch {
                        project_name: project.name.clone(),
                        project_path: project.path.clone(),
                        relative_path: relative(&project.path, &path),
                        path,
                        bytes: size.bytes,
                        file_count: size.files,
                    });
                    if out.len() >= limit {
                        break 'projects;
                    }
                    continue;
                }
                if depth + 1 < MAX_DEPTH {
                    stack.push((path, depth + 1));
                }
            }
        }
    }
    out.sort_by_key(|m| std::cmp::Reverse(m.bytes));
    out
}

/// Names that are never treated as artifacts, whatever the rules say.
/// Simple globs: `*` matches any run of characters.
pub const PROTECTED_PATTERNS: &[&str] = &[
    "src",
    "app",
    "pages",
    "public",
    "assets",
    "uploads",
    "data",
    "migrations",
    ".git",
    ".env",
    ".env.*",
    "*.db",
    "*.sqlite",
    "*.sqlite3",
    "README*",
    "package.json",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "Cargo.toml",
    "Cargo.lock",
    "pyproject.toml",
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "poetry.lock",
    "uv.lock",
    "go.mod",
    "go.sum",
    "Gemfile",
    "Gemfile.lock",
    "composer.json",
    "composer.lock",
    "pubspec.yaml",
    "pubspec.lock",
    "Podfile",
    "Podfile.lock",
];

pub fn is_protected_name(name: &str) -> bool {
    PROTECTED_PATTERNS.iter().any(|p| glob_match(p, name))
}

/// Minimal glob matcher supporting `*` (any run of characters, including
/// none). Case-sensitive on purpose: rules name directories exactly.
pub fn glob_match(pattern: &str, name: &str) -> bool {
    fn go(p: &[u8], n: &[u8]) -> bool {
        match p.first() {
            None => n.is_empty(),
            Some(b'*') => {
                let rest = &p[1..];
                (0..=n.len()).any(|i| go(rest, &n[i..]))
            }
            Some(&c) => n.first() == Some(&c) && go(&p[1..], &n[1..]),
        }
    }
    go(pattern.as_bytes(), name.as_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn glob_matching() {
        assert!(glob_match("node_modules", "node_modules"));
        assert!(!glob_match("node_modules", "node_modules2"));
        assert!(glob_match("*.egg-info", "pointsy.egg-info"));
        assert!(glob_match(".env.*", ".env.local"));
        assert!(!glob_match(".env.*", ".env"));
        assert!(glob_match("README*", "README.md"));
        assert!(glob_match("*", "anything"));
    }

    #[test]
    fn ecosystem_specific_rules_win() {
        let rules = RuleSet::builtin();
        let rust = rules.match_for("target", &[Stack::Rust]).unwrap();
        assert_eq!(rust.category, ArtifactCategory::RustTarget);
        let maven = rules.match_for("target", &[Stack::Maven]).unwrap();
        assert_eq!(maven.category, ArtifactCategory::BuildArtifacts);
        // `target` in a Node-only project is not an artifact.
        assert!(rules.match_for("target", &[Stack::Node]).is_none());
        // Generic `.cache` applies everywhere.
        assert!(rules.match_for(".cache", &[Stack::Go]).is_some());
    }

    #[test]
    fn protected_names_never_match() {
        let custom = vec![CleanupRule {
            id: "evil".into(),
            pattern: "src".into(),
            ecosystems: vec![],
            safety: Safety::Safe,
            regeneratable: true,
            category: ArtifactCategory::Other,
            explanation: String::new(),
            restore_hint: None,
            builtin: false,
        }];
        let rules = RuleSet::with_custom(&custom, &[]);
        assert!(rules.match_for("src", &[Stack::Node]).is_none());
        assert!(rules.find("evil").is_none());
        assert!(is_protected_name(".env.production"));
        assert!(is_protected_name("app.sqlite"));
        assert!(!is_protected_name("node_modules"));
    }

    #[test]
    fn custom_rules_apply() {
        let custom = vec![CleanupRule {
            id: "storybook-cache".into(),
            pattern: ".storybook-cache".into(),
            ecosystems: vec![],
            safety: Safety::Safe,
            regeneratable: true,
            category: ArtifactCategory::Caches,
            explanation: "Storybook cache".into(),
            restore_hint: None,
            builtin: false,
        }];
        let rules = RuleSet::with_custom(&custom, &["generated-*".to_string()]);
        assert!(rules.is_protected("generated-sdk"));
        assert!(rules
            .match_for(".storybook-cache", &[Stack::Node])
            .is_some());
        assert!(rules.is_barrier(".storybook-cache"));
    }
}
