//! Core data model shared between the engine, the CLI, and the desktop UI.
//! Everything here serialises to camelCase JSON so the TypeScript types in
//! `src/types/` mirror it one-to-one.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// A technology ecosystem detected from marker files in a project root.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Stack {
    Node,
    Rust,
    Python,
    Go,
    Maven,
    Gradle,
    DotNet,
    CocoaPods,
    Dart,
    Ruby,
    Php,
    Swift,
    Elixir,
    Haskell,
    Zig,
    Unity,
    Terraform,
}

impl Stack {
    pub const ALL: [Stack; 17] = [
        Stack::Node,
        Stack::Rust,
        Stack::Python,
        Stack::Go,
        Stack::Maven,
        Stack::Gradle,
        Stack::DotNet,
        Stack::CocoaPods,
        Stack::Dart,
        Stack::Ruby,
        Stack::Php,
        Stack::Swift,
        Stack::Elixir,
        Stack::Haskell,
        Stack::Zig,
        Stack::Unity,
        Stack::Terraform,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Stack::Node => "Node",
            Stack::Rust => "Rust",
            Stack::Python => "Python",
            Stack::Go => "Go",
            Stack::Maven => "Maven",
            Stack::Gradle => "Gradle",
            Stack::DotNet => ".NET",
            Stack::CocoaPods => "CocoaPods",
            Stack::Dart => "Dart",
            Stack::Ruby => "Ruby",
            Stack::Php => "PHP",
            Stack::Swift => "Swift",
            Stack::Elixir => "Elixir",
            Stack::Haskell => "Haskell",
            Stack::Zig => "Zig",
            Stack::Unity => "Unity",
            Stack::Terraform => "Terraform",
        }
    }

    /// Lenient parsing for CLI flags and config files.
    pub fn parse(s: &str) -> Option<Stack> {
        Some(match s.trim().to_ascii_lowercase().as_str() {
            "node" | "nodejs" | "node.js" | "javascript" | "js" | "typescript" | "ts" => {
                Stack::Node
            }
            "rust" | "cargo" => Stack::Rust,
            "python" | "py" => Stack::Python,
            "go" | "golang" => Stack::Go,
            "maven" | "java" => Stack::Maven,
            "gradle" | "kotlin" | "android" => Stack::Gradle,
            "dotnet" | ".net" | "csharp" | "c#" => Stack::DotNet,
            "cocoapods" | "pods" | "ios" => Stack::CocoaPods,
            "dart" | "flutter" => Stack::Dart,
            "ruby" | "bundler" => Stack::Ruby,
            "php" | "composer" => Stack::Php,
            "swift" | "spm" => Stack::Swift,
            "elixir" | "mix" | "phoenix" => Stack::Elixir,
            "haskell" | "cabal" | "stack" => Stack::Haskell,
            "zig" => Stack::Zig,
            "unity" => Stack::Unity,
            "terraform" | "opentofu" | "tofu" => Stack::Terraform,
            _ => return None,
        })
    }
}

/// How safe it is to remove an artifact. Mirrors the green / amber / red
/// levels from the product specification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Safety {
    /// Green: regenerated by the toolchain from committed inputs.
    Safe,
    /// Amber: usually regeneratable, but behaviour varies. Never bulk-selected
    /// unless the user opts in.
    Review,
    /// Red: never removed automatically.
    Protected,
}

/// Category used for the "reclaimable storage by category" breakdown.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ArtifactCategory {
    NodeDependencies,
    RustTarget,
    BuildArtifacts,
    PythonEnvironments,
    Caches,
    Other,
}

impl ArtifactCategory {
    pub const ALL: [ArtifactCategory; 6] = [
        ArtifactCategory::NodeDependencies,
        ArtifactCategory::RustTarget,
        ArtifactCategory::BuildArtifacts,
        ArtifactCategory::PythonEnvironments,
        ArtifactCategory::Caches,
        ArtifactCategory::Other,
    ];

    pub fn label(self) -> &'static str {
        match self {
            ArtifactCategory::NodeDependencies => "Node dependencies",
            ArtifactCategory::RustTarget => "Rust target",
            ArtifactCategory::BuildArtifacts => "Build artifacts",
            ArtifactCategory::PythonEnvironments => "Python environments",
            ArtifactCategory::Caches => "Caches",
            ArtifactCategory::Other => "Other",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProjectStatus {
    Active,
    Dormant,
    Hibernated,
    Protected,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GitState {
    Clean,
    Modified,
    Untracked,
    NoRepo,
    RemoteMissing,
    Unknown,
}

impl GitState {
    pub fn label(self) -> &'static str {
        match self {
            GitState::Clean => "Clean",
            GitState::Modified => "Modified",
            GitState::Untracked => "Untracked files",
            GitState::NoRepo => "No Git repository",
            GitState::RemoteMissing => "Remote missing",
            GitState::Unknown => "Unknown",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GitInfo {
    pub is_repo: bool,
    pub state: GitState,
    pub is_clean: Option<bool>,
    pub modified_count: u32,
    pub untracked_count: u32,
    pub remote_configured: Option<bool>,
    pub branch: Option<String>,
    pub last_commit_at: Option<DateTime<Utc>>,
}

impl GitInfo {
    pub fn no_repo() -> Self {
        GitInfo {
            is_repo: false,
            state: GitState::NoRepo,
            is_clean: None,
            modified_count: 0,
            untracked_count: 0,
            remote_configured: None,
            branch: None,
            last_commit_at: None,
        }
    }
}

/// A directory inside a project that a cleanup rule matched.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CleanupArtifact {
    /// Absolute path of the directory.
    pub path: PathBuf,
    /// Path relative to the project root, always with `/` separators and a
    /// trailing slash, e.g. `apps/web/.next/`.
    pub relative_path: String,
    /// Rule id that matched, e.g. `node_modules`.
    pub kind: String,
    pub category: ArtifactCategory,
    pub bytes: u64,
    pub file_count: u64,
    pub dir_count: u64,
    pub safety: Safety,
    pub regeneratable: bool,
    /// Why this can be removed, in one sentence.
    pub explanation: String,
    /// The command that brings it back, when known.
    pub restore_hint: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HibernationRecord {
    pub hibernated_at: DateTime<Utc>,
    pub previous_bytes: u64,
    pub saved_bytes: u64,
    pub history_entry_id: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivitySources {
    pub source_modified_at: Option<DateTime<Utc>>,
    pub git_commit_at: Option<DateTime<Utc>>,
    pub app_activity_at: Option<DateTime<Utc>>,
}

impl ActivitySources {
    pub fn latest(&self) -> Option<DateTime<Utc>> {
        [
            self.source_modified_at,
            self.git_commit_at,
            self.app_activity_at,
        ]
        .into_iter()
        .flatten()
        .max()
    }
}

/// The primary object in the UI.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    /// Stable id derived from the canonical path.
    pub id: String,
    pub name: String,
    pub path: PathBuf,
    /// The scan root this project was found under.
    pub scan_root: PathBuf,
    /// Enclosing project when this is a nested project.
    pub parent_path: Option<PathBuf>,
    pub stacks: Vec<Stack>,
    /// Frameworks / flavours, e.g. `Next.js`, `TypeScript`, `Flutter`.
    pub frameworks: Vec<String>,
    /// Relative paths of workspace members folded into this project
    /// (`apps/web`, `crates/core`, …).
    #[serde(default)]
    pub workspace_members: Vec<String>,
    /// How long measuring this project took, for slow-folder hints.
    #[serde(default)]
    pub scan_duration_ms: u64,
    /// Artifact trees whose sizes were reused from the previous scan.
    #[serde(default)]
    pub cache_hits: u32,
    pub package_manager: Option<String>,
    pub total_bytes: u64,
    /// Bytes in green (safe) artifacts.
    pub reclaimable_bytes: u64,
    /// Bytes in amber (review) artifacts.
    pub review_bytes: u64,
    pub file_count: u64,
    pub last_activity_at: Option<DateTime<Utc>>,
    pub activity: ActivitySources,
    pub git: Option<GitInfo>,
    pub status: ProjectStatus,
    /// Project-level safety: `Review` when something deserves a second look
    /// before hibernating (uncommitted changes, review-only artifacts).
    pub safety: Safety,
    pub safety_reasons: Vec<String>,
    pub artifacts: Vec<CleanupArtifact>,
    /// Top-level entries that match protected patterns (`src/`, `.env`, ...).
    pub protected_entries: Vec<String>,
    pub protected: bool,
    pub ignored_until: Option<DateTime<Utc>>,
    pub hibernation: Option<HibernationRecord>,
    pub scanned_at: DateTime<Utc>,
    pub warnings: Vec<String>,
}

impl Project {
    pub fn is_ignored(&self, now: DateTime<Utc>) -> bool {
        matches!(self.ignored_until, Some(until) if until > now)
    }

    pub fn artifact(&self, path: &Path) -> Option<&CleanupArtifact> {
        self.artifacts.iter().find(|a| a.path == path)
    }

    pub fn primary_label(&self) -> String {
        if let Some(fw) = self.frameworks.first() {
            if fw != "TypeScript" {
                return fw.clone();
            }
        }
        self.stacks
            .first()
            .map(|s| s.label().to_string())
            .unwrap_or_else(|| "Unknown".to_string())
    }
}

/// Stable, filesystem-independent id for a project path (FNV-1a 64).
pub fn project_id(path: &Path) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in path.to_string_lossy().as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Sentinel used for "ignore until manually restored".
pub fn ignore_forever() -> DateTime<Utc> {
    DateTime::parse_from_rfc3339("9999-12-31T00:00:00Z")
        .expect("valid sentinel")
        .with_timezone(&Utc)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn project_ids_are_stable_and_distinct() {
        let a = project_id(Path::new("/home/dev/Projects/pointsy"));
        let b = project_id(Path::new("/home/dev/Projects/pointsy"));
        let c = project_id(Path::new("/home/dev/Projects/pointsy2"));
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.len(), 16);
    }

    #[test]
    fn stack_parsing_is_lenient() {
        assert_eq!(Stack::parse("Node.js"), Some(Stack::Node));
        assert_eq!(Stack::parse(".NET"), Some(Stack::DotNet));
        assert_eq!(Stack::parse("flutter"), Some(Stack::Dart));
        assert_eq!(Stack::parse("cobol"), None);
    }

    #[test]
    fn serialises_camel_case() {
        let json = serde_json::to_string(&ArtifactCategory::NodeDependencies).unwrap();
        assert_eq!(json, "\"nodeDependencies\"");
        let json = serde_json::to_string(&Stack::DotNet).unwrap();
        assert_eq!(json, "\"dotnet\"");
    }
}
